# Generated by Django 4.1.2 on 2022-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeeps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=15)),
                ('cilindrada', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=30)),
                ('año', models.CharField(max_length=30)),
            ],
        ),
    ]
